In [1]:
# Importing necessary libraries for data analysis and visualization
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Verify imports
print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:
from google.colab import files
files_to_load=files.upload()

Saving EuroCrop_agricultural_logistics_dataset.csv to EuroCrop_agricultural_logistics_dataset.csv

In [3]:
# Load the dataset
df = pd.read_csv("EuroCrop_agricultural_logistics_dataset.csv")

# Displaying a success message
print(f"Successfully loaded the dataset with {df.shape[0]} rows and {df.shape[1]} columns.")

Successfully loaded the dataset with 53305 rows and 29 columns.

In [4]:
# Display first 10 rows
print("First 10 Rows of the Dataset:")
df.head(10)

First 10 Rows of the Dataset:

,Unnamed: 0,Vehicle_Type,Crop_Type,Harvest_Date,Crop_Yield,Storage_Temperature,Storage_Humidity,Fuel_Consumption,Route_Distance,Delivery_Time,...,Energy_Consumption,IoT_Sensor_Reading_Temperature,IoT_Sensor_Reading_Humidity,IoT_Sensor_Reading_Light,Warehouse_Storage_Time,Inventory_Levels,Fuel_Costs,Spoilage_Risk,Efficiency_Ratio,Quality_Maintenance_Ratio
0,2018-06-01 00:00:00,Truck,Wheat,2017-01-20,inf,2010.925417,5.643389e+33,5.239564e+11,2.318451e+266,3468.336745,...,inf,3.658898e+19,1.170482e+23,3.856542e+246,9.830356e+06,inf,80.803108,1.105630,inf,34.426335
1,2018-06-01 01:00:00,Motorbike,Corn,2017-05-10,inf,136355.031210,6.952133e+31,1.953551e+06,8.123388e+278,81.403614,...,inf,2.783849e+16,3.042830e+32,5.801202e+139,1.748252e+09,inf,259.542890,1.184757,inf,10.515091
2,2018-06-01 02:00:00,Van,Corn,2017-09-19,inf,1729.900510,3.998236e+23,1.811603e+09,8.253634e+278,344.008165,...,inf,5.195060e+13,6.635070e+29,3.371894e+162,1.265088e+10,inf,144.204018,1.117353,2.272234e+302,61.892903
3,2018-06-01 03:00:00,Truck,Corn,2017-03-19,inf,3322.905892,9.876549e+46,1.688319e+11,6.589420e+211,1027.148001,...,inf,3.581963e+19,8.244667e+18,6.650533e+167,3.753014e+06,inf,851.083719,1.086061,inf,133.447750
4,2018-06-01 04:00:00,Truck,Corn,2017-12-11,inf,103.635996,5.751421e+35,8.263637e+10,1.476641e+250,95.009621,...,inf,5.108956e+09,1.479540e+37,1.603527e+215,3.090519e+03,inf,8.101715,1.167187,inf,12.884975
5,2018-06-01 05:00:00,Truck,Corn,2017-04-12,inf,3377.481589,4.929694e+36,4.506809e+09,5.443379e+244,341936.665929,...,inf,6.106514e+14,1.042049e+18,4.109824e+171,1.175258e+07,inf,86.212776,1.258438,inf,43.692709
6,2018-06-01 06:00:00,Truck,Corn,2017-02-06,inf,1284.938790,3.021769e+29,4.156817e+10,1.573185e+238,89968.094065,...,inf,1.823919e+15,1.210697e+26,4.181133e+206,3.229212e+08,inf,629.980993,1.203992,inf,16.324561
7,2018-06-01 07:00:00,Van,Wheat,2017-08-08,inf,386.136500,6.540998e+24,5.114542e+14,6.989792e+175,2897.140264,...,inf,4.516657e+15,1.360982e+20,3.874027e+170,4.295452e+08,inf,9.099062,1.179586,inf,6.030063
8,2018-06-01 08:00:00,Truck,Rice,2017-05-02,inf,22880.434106,8.002837e+35,7.352494e+11,8.407846e+194,1501.335038,...,inf,2.967856e+17,1.559427e+25,1.051731e+266,9.200849e+05,inf,22.886851,1.118978,inf,47.855649
9,2018-06-01 09:00:00,Van,Rice,2017-07-18,inf,2208.917078,1.346927e+24,5.499756e+08,2.215593e+252,982619.068274,...,inf,8.539326e+14,1.393935e+33,1.469563e+249,7.151647e+01,inf,49.978330,1.179459,inf,43.493033

In [5]:
# Display last 10 rows
print("Last 10 Rows of the Dataset:")
df.tail(10)

Last 10 Rows of the Dataset:

,Unnamed: 0,Vehicle_Type,Crop_Type,Harvest_Date,Crop_Yield,Storage_Temperature,Storage_Humidity,Fuel_Consumption,Route_Distance,Delivery_Time,...,Energy_Consumption,IoT_Sensor_Reading_Temperature,IoT_Sensor_Reading_Humidity,IoT_Sensor_Reading_Light,Warehouse_Storage_Time,Inventory_Levels,Fuel_Costs,Spoilage_Risk,Efficiency_Ratio,Quality_Maintenance_Ratio
53295,2024-06-29 15:00:00,Truck,Wheat,2017-04-25,inf,1.158198e+04,3.876046e+29,1.462194e+08,4.732793e+221,6280.624166,...,inf,4.237873e+18,6.818287e+14,5.009324e+242,1.065761e+05,inf,191.090515,1.194627,inf,5.526027
53296,2024-06-29 16:00:00,Truck,Corn,2017-07-05,inf,3.264789e+04,1.009435e+42,9.747493e+12,2.588159e+225,1342.281842,...,inf,3.048111e+09,2.255022e+25,4.419738e+202,1.241098e+07,inf,103.155514,1.212074,inf,2.205892
53297,2024-06-29 17:00:00,Truck,Corn,2017-06-01,inf,1.321177e+03,2.132835e+28,8.917259e+11,2.920869e+223,37405.419777,...,inf,3.755189e+19,8.290863e+21,9.002884e+212,1.154281e+09,inf,215.969414,1.151413,inf,16.389407
53298,2024-06-29 18:00:00,Van,Corn,2017-02-26,inf,7.811580e+02,1.441914e+41,1.680684e+13,2.483361e+198,180622.742469,...,inf,5.883107e+16,5.640102e+28,1.137203e+194,3.470753e+07,inf,37.630156,1.153639,inf,8.472842
53299,2024-06-29 19:00:00,Truck,Rice,2017-03-05,inf,3.448350e-01,4.699880e+44,4.084754e+11,1.542776e+236,37356.981753,...,inf,7.479209e+21,6.869762e+21,2.591789e+185,7.239022e+07,inf,119.625416,0.996437,inf,65.331597
53300,2024-06-29 20:00:00,Truck,Corn,2017-09-05,inf,1.254483e+01,1.046057e+23,1.150468e+12,5.038663e+201,73.180202,...,inf,1.524798e+10,5.182480e+27,8.545286e+190,1.437318e+09,inf,19.372429,1.069245,inf,105.366359
53301,2024-06-29 21:00:00,Truck,Wheat,2017-09-27,inf,5.769750e+07,9.327460e+32,4.224318e+11,4.710606e+307,2181.626165,...,inf,3.823817e+13,1.911910e+19,2.204625e+206,1.840043e+04,inf,94.879811,1.159118,inf,27.042055
53302,2024-06-29 22:00:00,Van,Corn,2017-05-20,inf,1.216248e+04,1.691420e+49,1.926252e+09,inf,15559.880624,...,inf,7.493926e+15,2.700061e+22,7.027383e+220,1.145098e+05,inf,19.233654,1.224539,inf,9.124795
53303,2024-06-29 23:00:00,Truck,Corn,2017-02-18,inf,1.313343e+03,1.018104e+40,4.264034e+09,5.911150e+219,25946.182979,...,inf,2.683308e+20,1.365068e+26,2.052028e+210,3.398438e+08,inf,17.594886,1.167377,inf,17.153431
53304,2024-06-30 00:00:00,Van,Wheat,2017-04-06,inf,3.350260e+02,5.914906e+26,2.399370e+12,1.126394e+209,619.209488,...,inf,6.673823e+18,3.274274e+26,2.667876e+147,2.129012e+11,inf,324.387475,1.112764,inf,47.512335

In [6]:
# 1. Checking the shape of the data
print("Dataset Shape:", df.shape)

# 2. Getting a summary of columns, non-null counts, and data types
print("\nData Information")
df.info()

# 3. Generating statistical summaries for numerical columns
print("\nDescriptive Statistics")
display(df.describe())

Dataset Shape: (53305, 29)

Data Information
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53305 entries, 0 to 53304
Data columns (total 29 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Unnamed: 0                      53305 non-null  object
 1   Vehicle_Type                    53305 non-null  object
 2   Crop_Type                       53305 non-null  object
 3   Harvest_Date                    53305 non-null  object
 4   Crop_Yield                      53305 non-null  float64
 5   Storage_Temperature             53305 non-null  float64
 6   Storage_Humidity                53305 non-null  float64
 7   Fuel_Consumption                53305 non-null  float64
 8   Route_Distance                  53305 non-null  float64
 9   Delivery_Time                   53305 non-null  float64
 10  Traffic_Level                   53305 non-null  float64
 11  Temperature                     53305 non-null  float64
 12  Humidity                        53305 non-null  float64
 13  Vehicle_Load_Capacity           53305 non-null  float64
 14  Vibration_Level                 53305 non-null  float64
 15  Queue_Time                      53305 non-null  float64
 16  Weather_Impact                  53305 non-null  float64
 17  Station_Capacity                53305 non-null  float64
 18  Operational_Cost                53305 non-null  float64
 19  Energy_Consumption              53305 non-null  float64
 20  IoT_Sensor_Reading_Temperature  53305 non-null  float64
 21  IoT_Sensor_Reading_Humidity     53305 non-null  float64
 22  IoT_Sensor_Reading_Light        53305 non-null  float64
 23  Warehouse_Storage_Time          53305 non-null  float64
 24  Inventory_Levels                53305 non-null  float64
 25  Fuel_Costs                      53305 non-null  float64
 26  Spoilage_Risk                   53305 non-null  float64
 27  Efficiency_Ratio                53305 non-null  float64
 28  Quality_Maintenance_Ratio       53305 non-null  float64
dtypes: float64(25), object(4)
memory usage: 11.8+ MB

Descriptive Statistics

/usr/local/lib/python3.13/dist-packages/numpy/lib/_function_base_impl.py:4620: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
/usr/local/lib/python3.13/dist-packages/numpy/lib/_function_base_impl.py:4620: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
/usr/local/lib/python3.13/dist-packages/numpy/lib/_function_base_impl.py:4620: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
/usr/local/lib/python3.13/dist-packages/numpy/lib/_function_base_impl.py:4620: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
/usr/local/lib/python3.13/dist-packages/numpy/lib/_function_base_impl.py:4620: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
/usr/local/lib/python3.13/dist-packages/numpy/lib/_function_base_impl.py:4620: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
/usr/local/lib/python3.13/dist-packages/numpy/lib/_function_base_impl.py:4620: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)

,Crop_Yield,Storage_Temperature,Storage_Humidity,Fuel_Consumption,Route_Distance,Delivery_Time,Traffic_Level,Temperature,Humidity,Vehicle_Load_Capacity,...,Energy_Consumption,IoT_Sensor_Reading_Temperature,IoT_Sensor_Reading_Humidity,IoT_Sensor_Reading_Light,Warehouse_Storage_Time,Inventory_Levels,Fuel_Costs,Spoilage_Risk,Efficiency_Ratio,Quality_Maintenance_Ratio
count,53305.0,5.330500e+04,5.330500e+04,5.330500e+04,5.330500e+04,5.330500e+04,5.330500e+04,5.330500e+04,5.330500e+04,53305.0,...,5.330500e+04,5.330500e+04,5.330500e+04,5.330500e+04,5.330500e+04,53305.0,53305.000000,53305.000000,5.330500e+04,53305.000000
mean,inf,1.277650e+05,1.190139e+69,3.242603e+16,inf,1.386396e+06,7.819425e+85,3.478350e+41,1.204144e+80,inf,...,inf,1.667742e+25,1.864675e+51,inf,1.423602e+13,inf,182.747029,1.163523,inf,88.316161
std,NaN,1.838983e+06,2.746448e+71,2.207349e+18,NaN,5.629696e+07,1.737923e+88,7.864278e+43,2.780093e+82,NaN,...,NaN,1.262342e+27,4.299602e+53,NaN,9.629340e+14,NaN,336.012417,0.070087,NaN,323.469499
min,0.0,3.616935e-03,2.762129e-11,2.213121e-01,9.892575e+77,2.103594e-03,4.234883e-33,1.012279e-08,6.468932e-02,0.0,...,1.992871e-104,1.264025e+03,1.309217e-02,7.511040e-108,7.886117e-03,inf,0.670411,0.891445,2.756807e+02,0.072954
25%,NaN,2.409128e+02,9.320194e+25,4.581364e+08,1.239347e+208,4.834077e+02,1.587157e+25,1.315587e+15,2.719328e+32,NaN,...,NaN,1.239868e+14,4.085134e+21,2.490889e+151,1.685331e+06,NaN,39.613976,1.115148,NaN,7.654343
50%,NaN,1.830611e+03,3.347062e+32,2.544027e+10,8.862395e+234,4.874129e+03,3.795008e+34,3.381144e+19,1.201043e+39,NaN,...,NaN,1.958523e+16,1.176226e+26,2.276999e+195,6.571410e+07,NaN,88.742657,1.161247,NaN,22.700866
75%,NaN,1.353617e+04,1.318937e+39,1.498957e+12,1.092224e+261,4.872172e+04,1.091023e+44,8.156426e+23,4.955221e+45,NaN,...,NaN,2.938107e+18,3.407367e+30,1.682421e+239,2.498499e+09,NaN,199.807277,1.209368,NaN,69.441500
max,inf,1.530941e+08,6.340965e+73,3.379066e+20,inf,1.105648e+10,4.009846e+90,1.815556e+46,6.418644e+84,inf,...,inf,1.460049e+29,9.926861e+55,inf,1.634005e+17,inf,15706.897123,1.458762,inf,26042.910868

In [8]:
print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

Missing values:
Unnamed: 0                        0
Vehicle_Type                      0
Crop_Type                         0
Harvest_Date                      0
Crop_Yield                        0
Storage_Temperature               0
Storage_Humidity                  0
Fuel_Consumption                  0
Route_Distance                    0
Delivery_Time                     0
Traffic_Level                     0
Temperature                       0
Humidity                          0
Vehicle_Load_Capacity             0
Vibration_Level                   0
Queue_Time                        0
Weather_Impact                    0
Station_Capacity                  0
Operational_Cost                  0
Energy_Consumption                0
IoT_Sensor_Reading_Temperature    0
IoT_Sensor_Reading_Humidity       0
IoT_Sensor_Reading_Light          0
Warehouse_Storage_Time            0
Inventory_Levels                  0
Fuel_Costs                        0
Spoilage_Risk                     0
Efficiency_Ratio                  0
Quality_Maintenance_Ratio         0
dtype: int64

Duplicate rows:
0